language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
    - master
python:
    - '2.7'

install:
  - pip install pyflakes
  - pip install codecov
  - pip install pretend
  - pip install .

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=lint

# no pep8, since vertex uses twisted pep8
script:
  ./.travis/run.sh

after_success:
  - codecov

notifications:
  email: false
  irc:
     channels: "chat.freenode.net#divmod"
     template:
       - "%{repository}@%{branch} - %{author}: %{message} (%{build_url})"
     use_notice: true
